name: imitation_learning
dependencies:
    - python=3.6
    - numpy
    - matplotlib
    - jupyter
    - h5py
    - flask-socketio
    - scikit-learn
    - tensorflow-gpu
    #- keras
    - pip:
        - eventlet
        - opencv-python
