name: imitation_learning
dependencies:
    - python=2.7
    - numpy
    - matplotlib
    - jupyter
    - h5py
    - flask-socketio
    - tensorflow-gpu
    - pip:
        - eventlet
        - opencv-python